version: '3.6'

services:
  nginx:
    build: ./config/
    ports: 
    - 80:80

  flaskapp:
    build: ./
    environment:
      MONGODB_DATABASE: Project
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: 123
      MONGODB_HOSTNAME: mongodb
    ports:
    - 5000:5000
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: Project
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null